---
- hosts: all
  become: true
  tasks:
  - name: Install Haproxy
    apt:
      name: haproxy
      state: present

  - name: Copy Haproxy Configuration file
    copy:
      src: templates/haproxy.cfg
      dest: /etc/haproxy/haproxy.cfg
